# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: python
      language_version: python3
      types: [python]
    - id: black
      name: black
      entry: black
      language: python
      language_version: python3
      types: [python]
    - id: bandit
      name: bandit
      entry: bandit --ini .bandit
      language: python
      language_version: python3
      types: [python]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      language_version: python3
      types: [python]