service: fastapi-serverless-starter
package:
  individually: true
provider:
  name: aws
  profile: ${opt:aws-profile, "default"}
  stage: ${opt:stage, "dev"}
  runtime: python3.9
  stackTags:
    Owner: 'Massimo Biagioli'
    Destroy: 'false'

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true

functions:
  app:
    handler: fastapi_serverless_starter.lambda.handler
    events:
      - http:
          method: get
          path: /
      - http:
          method: any
          path: /{proxy+}